{{- if .Values.nfs.enabled -}}
# Source: dlf-chart/charts/csi-nfs-chart/templates/csi-attacher-rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-attacher-runner-nfs
  labels:
    app.kubernetes.io/name: "dlf"
  namespace: dlf
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
# Source: dlf-chart/charts/csi-nfs-chart/templates/csi-nodeplugin-rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-nodeplugin
  labels:
    app.kubernetes.io/name: "dlf"
  namespace: dlf
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
---
# Source: dlf-chart/charts/csi-nfs-chart/templates/csi-attacher-rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-attacher-role-nfs
  labels:
    app.kubernetes.io/name: "dlf"
  namespace: dlf
subjects:
  - kind: ServiceAccount
    name: csi-attacher-nfs
    namespace: dlf
roleRef:
  kind: ClusterRole
  name: external-attacher-runner-nfs
  apiGroup: rbac.authorization.k8s.io
---
# Source: dlf-chart/charts/csi-nfs-chart/templates/csi-nodeplugin-rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-nodeplugin
  labels:
    app.kubernetes.io/name: "dlf"
  namespace: dlf
subjects:
  - kind: ServiceAccount
    name: csi-nodeplugin
    namespace: dlf
roleRef:
  kind: ClusterRole
  name: csi-nodeplugin
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
