# Source: dlf-chart/charts/dataset-operator-chart/templates/apps/operator.yaml
apiVersion: v1
kind: Service
metadata:
  name: webhook-server
  labels:
    app.kubernetes.io/name: "dlf"
spec:
  selector:
    name: dataset-operator
  ports:
    - port: 443
      targetPort: webhook-api