{{- if .Values.h3.enabled -}}
# Source: dlf-chart/charts/csi-h3-chart/templates/csi-controller-rbac.yaml
# This YAML file contains RBAC API objects that are necessary to run external
# CSI attacher for H3 adapter

apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-controller-h3
  labels:
    app.kubernetes.io/name: "dlf"
  namespace: dlf
---
# Source: dlf-chart/charts/csi-h3-chart/templates/csi-nodeplugin-rbac.yaml
# This YAML defines all API objects to create RBAC roles for CSI node plugin

apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-nodeplugin-h3
  labels:
    app.kubernetes.io/name: "dlf"
  namespace: dlf
{{- end -}}
