{{- if .Values.s3.enabled -}}
# Source: dlf-chart/charts/csi-s3-chart/templates/attacher.yaml
# needed for StatefulSet
kind: Service
apiVersion: v1
metadata:
  name: csi-attacher-s3
  namespace: dlf
  labels:
    app: csi-attacher-s3
    app.kubernetes.io/name: "dlf"
spec:
  selector:
    app: csi-attacher-s3
  ports:
    - name: dummy
      port: 12345
---
# Source: dlf-chart/charts/csi-s3-chart/templates/provisioner.yaml
kind: Service
apiVersion: v1
metadata:
  name: csi-provisioner-s3
  namespace: dlf
  labels:
    app: csi-provisioner-s3
    app.kubernetes.io/name: "dlf"
spec:
  selector:
    app: csi-provisioner-s3
  ports:
    - name: dummy
      port: 12345
{{- end -}}
