{{- if .Values.nfs.enabled -}}
# Source: dlf-chart/charts/csi-nfs-chart/templates/csi-attacher-rbac.yaml
# This YAML file contains RBAC API objects that are necessary to run external
# CSI attacher for nfs flex adapter

apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-attacher-nfs
  labels:
    app.kubernetes.io/name: "dlf"
  namespace: dlf
---
# Source: dlf-chart/charts/csi-nfs-chart/templates/csi-nodeplugin-rbac.yaml
# This YAML defines all API objects to create RBAC roles for CSI node plugin
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-nodeplugin
  labels:
    app.kubernetes.io/name: "dlf"
  namespace: dlf
{{- end -}}
