{{- if .Values.s3.enabled -}}
# Source: dlf-chart/charts/csi-s3-chart/templates/csi-s3.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-s3
  labels:
    app.kubernetes.io/name: "dlf"
  namespace: dlf
{{- end -}}
