version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
  - package-ecosystem: "pip"
    directory: "/git_services"
    schedule:
      interval: "daily"
    target-branch: "master"
  - package-ecosystem: "gomod"
    directory: "/git-https-proxy"
    schedule:
      interval: "daily"
    target-branch: "master"
  - package-ecosystem: "gomod"
    directory: "/k8s-watcher"
    schedule:
      interval: "daily"
    target-branch: "master"
