version: 2
updates:
  - package-ecosystem: "pip"
    directories: 
      - "/"
      - "/git_services"
    schedule:
      interval: "daily"
    target-branch: "master"
    groups:
      python:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    groups:
      gh-actions:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directories: 
      - "/git-https-proxy"
      - "/k8s-watcher"
    schedule:
      interval: "daily"
    target-branch: "master"
    groups:
      gomod:
        patterns:
          - "*"
