# The datashim helm chart has no option to skip installing the crds
# This patch is used as a post-renderer in helm to remove the crds

resources:
  - all.yaml
patchesStrategicMerge:
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: datasets.com.ie.ibm.hpsys
    $patch: delete
  - |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: datasetsinternal.com.ie.ibm.hpsys
    $patch: delete
