repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
-   repo: local
    hooks:
    - id: chartpress
      name: chartpress reset
      files: helm-chart/*
      description: Run `chartpress --reset` to clean up helm charts before committing.
      entry: poetry run chartpress --reset
      language: system
      pass_filenames: false
