sudo: required
notifications:
  email: false
services:
- docker
language: python
python:
- 3.7
env:
  global:
  - HELM_URL=https://storage.googleapis.com/kubernetes-helm
  - HELM_TGZ=helm-v2.9.1-linux-amd64.tar.gz
  - secure: HtFlAJQ/+/mvqKKxOx3ANlaVxNvZWZs3Zbli+v7u1UyuDsluJocpiani2Gph8sl49lNJqr4TvGT/CuzJkT9yy/QbohTwPEI0ysbtr4WNyIOHfQ+JUSR548uzlUvfFjnzTZb/FX1zna22Ho4zGl89ikwIKEY1vvLsDnJ+LcZtP6y62q3flrzGuFluA9iPtYmalnm+irgaIOztda2+/sVCNtq6ld5c7P3WSYSkbgv3RNrec9KZ8DDWdFq6GKXfQscsNqDmkZDuvCoNlt/xnldqLhciR+j6PV1Xrf/ojPqgnxqyZnpGsKykrLnPCxBbhhD8Ei7qIT+OU2kqPf5GkIbG0KySrpG03A7vwhv1Wk2IzB6uQHkImjYbi3+GmjyKUxo4uKOZiXyJ8lG/7/H66qgoWx1QikaVjrnrBNQX3YqoNNxuXs8DZuFhQQZX9qYSWJ6KwYKHIw9eyIh95zSXnoquxW+HABiHO5Sz2e+B2wqbVDSI1ln4zoGd7o/rHlEXX7pplc+ET3cvNSb/wqWZ87EdqKc1pZScuPg1d4rSvtV4/TDCholefvRe0Xo6LzzXxcD+ErH/ouOZ2PGdGKEkk1kbC1zH1teFZQOb+v2oYG+OKncpAoXN2O5R4dOLk9LErjcTHe7+EVE+ZibRSt2jl5nTGslZVwZogFp/V8toE6P78Ts=
git:
  depth: false
install:
- travis_retry pip install -U pip pipenv
- travis_retry pipenv install --deploy --dev --system
- mkdir -p /tmp/helm
- wget -q ${HELM_URL}/${HELM_TGZ} -O /tmp/helm/${HELM_TGZ}
- tar -C /tmp/helm -xzv -f /tmp/helm/${HELM_TGZ}
- PATH=/tmp/helm/linux-amd64/:$PATH
- helm init --client-only
- docker pull renku/renku-notebooks:latest
- docker pull renku/jupyterhub-k8s:latest
- docker pull renku/git-clone:latest
script:
- pytest
- echo "building renku-notebooks"
- docker build .
- helm repo add jupyterhub https://jupyterhub.github.io/helm-chart
- helm dependency update helm-chart/renku-notebooks
- chartpress
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./.travis/travis-deploy.sh
  on:
    branch: master
    repo: SwissDataScienceCenter/renku-notebooks
- provider: script
  skip_cleanup: true
  script: bash ./.travis/travis-deploy.sh
  on:
    branch: master
    repo: SwissDataScienceCenter/renku-notebooks
    tags: true
