FROM python:3.7-slim

LABEL maintainer="info@datascience.ch"

RUN pip install --no-cache-dir --disable-pip-version-check -U pip poetry && \
    apt-get update && \
    apt-get install -y git && \
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && \
    apt-get install git-lfs && \
    git lfs install && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    groupadd -g 1000 kyaku && \
    useradd -u 1000 -g kyaku -m kyaku

USER 1000:1000

# Install renku
ENV PATH=$PATH:/home/kyaku/.renku/bin

RUN mkdir -p /home/kyaku/.renku/bin && \
    virtualenv /home/kyaku/.renku/venv && \
    . /home/kyaku/.renku/venv/bin/activate && \
    pip install --no-cache-dir setuptools==57.5.0 && \
    pip install --no-cache renku==0.16.1 && \
    deactivate && \
    ln -s /home/kyaku/.renku/venv/bin/renku /home/kyaku/.renku/bin/renku

# Install all packages
COPY pyproject.toml poetry.lock /home/kyaku/renku-notebooks/
WORKDIR /home/kyaku/renku-notebooks/
RUN poetry install

COPY renku_notebooks renku_notebooks
COPY resource_schema_migrations resource_schema_migrations
COPY tests tests

CMD ["poetry", "run", "pytest", "tests/integration"]
