apiVersion: v1
kind: Pod
metadata:
  name: test-git-clone
  namespace: tasko
spec:
  containers:
  - name: test
    image: alpine/git
    command:
      - "/bin/sh"
      - "-c"
    args:
      - "sleep 9999999"
    volumeMounts:
    - mountPath: /work
      name: data-test
  volumes:
  - name: data-test
    persistentVolumeClaim:
      claimName: data-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-test
  namespace: tasko
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: csi-cinder-sc-delete
