dependencies:
- name: amalthea
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.1.0
- name: certificates
  version: "0.0.1"
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"