dependencies:
- name: amalthea
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: "0.1.0"
- name: dlf-chart
  repository: "https://swissdatasciencecenter.github.io/datashim-charts/"
  version: "0.1.0"
