dependencies:
- name: amalthea
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.1.3
- name: certificates
  version: "0.11.0-rc1"
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
