dependencies:
- name: amalthea
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: "0.1.3"
- name: dlf-chart
  repository: "https://swissdatasciencecenter.github.io/datashim/"
  version: "0.1.1-rc7"
  condition: global.s3Datasets.enabled