dependencies:
- name: amalthea
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: 0.2.2
- name: certificates
  version: "0.11.0-rc2"
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
