dependencies:
- name: amalthea
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
  version: "0.5.2"
- name: certificates
  version: "0.0.3"
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
- name: dlf-chart
  repository: "https://swissdatasciencecenter.github.io/datashim/"
  version: "0.3.0-renku-1"
  condition: cloudstorage.s3.installDatashim
