# Default values for notebooks.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  useHTTPS: false
  gitlab:
    urlPrefix: /
  renku:
    domain:
  anonymousSessions:
    enabled: false
  ## Specify a secret that containes the certificate
  ## if you would like to use a custom CA. The key for the secret
  ## should have the .crt extension otherwise it is ignored. The
  ## keys across all secrets are mounted as files in one location so
  ## the keys across all secrets have to be unique.
  certificates:
    image:
      repository: renku/certificates
      tag: "0.0.1"
    customCAs:
      []
      # - secret:

amalthea:
  scope:
    clusterWide: false
  deployCrd: true
  ## If enabling S3 mounts uncomment the section below
  # extraChildResources:
  #   - name: datasets
  #     group: com.ie.ibm.hpsys

## Used only if S3 Mounts are enabled
dlf-chart:
  csi-sidecars-rbac:
    enabled: true
  csi-nfs-chart:
    enabled: false
  csi-s3-chart:
    mounter: "goofys"
    enabled: true
  csi-h3-chart:
    enabled: false
  dataset-operator-chart:
    enabled: true

cloudstorage:
  ## If enabled this will allow mounting of buckets into user sessions
  ## from any S3-compatible storage provider.
  s3:
    enabled: false
    installDatashim: false

# configuration for user session persistent volumes
userSessionPersistentVolumes:
  enabled: true
  # storageClass: leave undefined to use default, otherwise specify required class
  ## Prevents from applying size limits if emptyDirs are used for user sessions.
  ## This may be desirable because going over the limit for an emptyDir results in
  ## immediate eviction of the user session. EmptyDirs are used when the enabled flag
  ## above is set to false.
  useEmptyDirSizeLimit: false

gitlab:
  ## specify the GitLab instance URL
  url:
  registry:
    ## Set the default image registry
    host:

## For sending exceptions to Sentry, specify the DSN to use
sentry:
  enabled: false
  dsn:
  environment:
  ## Sample rate is used for performance monitoring in sentry
  sampleRate: 0.2
  
sessionSentry:
  gitClone:
    enabled: false
    dsn:
    environment:
    ## Sample rate is used for performance monitoring in sentry
    sampleRate: 0.2
  sidecar:
    enabled: false
    dsn:
    environment:
    ## Sample rate is used for performance monitoring in sentry
    sampleRate: 0.2

replicaCount: 2

## Configure autoscaling
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

image:
  repository: renku/renku-notebooks
  tag: "latest"
  pullPolicy: IfNotPresent

  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistrKeySecretName

# turns on flask debug mode
debug: true

# oidc settings
oidc:
  clientId: renku-jupyterserver
  clientSecret:
  tokenUrl:
  authUrl:
  allowUnverifiedEmail: false

sessionIngress:
  host:
  tlsSecret:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"

sessionAutosave:
  ## Any file higher than the minimum will be added to LFS
  minimumLFSFileSize: 5M
  ## How long should k8s wait for an autosave branch to be created before
  ## fully and forcefully removing a user session
  terminationGracePeriodSeconds: 600

## Setup node selector, tolerations and node affinities for user sessions that are launched
## by the notebook service. These can be used so that user sessions are only scheduled on
## dedicated nodes rather than on all nodes in a cluster. A strict setup where session pods
## are scheduled only on dedicated nodes and nothing else is scheduled on said nodes would involve:
## (i) taints on the nodes to prevent other non-session workloads from getting scheduled there,
## (ii) tolerations below to make sure the user session pods can get schedulded on the dedicated nodes,
## (iii) node affinity below to make sure the user sessions do not get scheduled on other nodes.
sessionNodeSelector: {}
sessionTolerations: []
sessionAffinity: {}

## Default server options - these will be provided to the user in the UI
## Note that requests are also limits, i.e. a user's jupyter kernel
## that exceeds the requested memory limit will be terminated/restarted.
serverOptions:
  defaultUrl:
    order: 1
    displayName: Default Environment
    type: enum
    default: /lab
    ## add /rstudio to the list for R projects
    options: [/lab]
  cpu_request:
    order: 2
    displayName: Number of CPUs
    type: enum
    default: 0.5
    options: [0.5, 1.0]
  mem_request:
    order: 3
    displayName: Amount of Memory
    type: enum
    default: 1G
    options: [1G, 2G]
  disk_request:
    order: 4
    displayName: Amount of Storage
    type: enum
    default: "1G"
    options: ["1G", "10G"]
    ## set allow_any_value to true to not enforce value checks
    ## arbitrary PV sizes
    # allow_any_value: true
    # value_range:
    #   type: bytes
    #   min: "1G"
    #   max: "100G"
  gpu_request:
    order: 5
    displayName: Number of GPUs
    type: enum
    default: 0
    options: [0]
  lfs_auto_fetch:
    order: 6
    displayName: Automatically fetch LFS data
    type: boolean
    default: false

## Default server option values used to launch a session when
## such values are not provided explicitly in the post request.
## It is mandatory to provide all of these to deploy the helm chart.
## The defaults below do not have to be equal to the default values
## specified in the server options for the UI above but they have to be
## within the available choices or valid ranges.
serverDefaults:
  defaultUrl: /lab
  cpu_request: 0.5
  mem_request: 1G
  disk_request: 1G
  gpu_request: 0
  lfs_auto_fetch: false

## How to enforce CPU limits for sessions, options are "lax", "off" or "strict"
## - "strict" = CPU limit equals cpu request
## - "lax" = CPU limit equals maximum from server_options, if CPU is not in server options then
##   CPU limit is set to the CPU request
## - "off" = no CPU limits at all
enforceCPULimits: "off"

## Default image used when the requested image for a user session cannot be found.
defaultSessionImage: "renku/renkulab-py:3.9-0.11.1"

gitRpcServer:
  image:
    name: renku/git-rpc-server
    tag: "latest"

gitHttpsProxy:
  image:
    name: renku/git-https-proxy
    tag: "latest"

gitClone:
  image:
    name: renku/git-clone
    tag: "latest"

service:
  type: ClusterIP
  port: 80

rbac:
  serviceAccountName: default
  create: true

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

culling:
  # How long before an idle session is removed from the cluster.
  # Setting a value of zero below makes it so that a session is never culled.
  idleThresholdSeconds:
    anonymous: 43200 # 12 hours
    registered: 86400 # 24 hours
  maxAgeSecondsThreshold:
    anonymous: 0 # do not cull sessions solely based on age (use activity)
    registered: 0 # do not cull sessions solely based on age (use activity)

tests:
  enabled: false
  oidc_issuer:
  gitlab_token:
  ## Specify the session types to be used in the tests, allowed values are 'registered' and/or 'anonymous'
  sessionTypes: ["registered"]
  image:
    repository: renku/renku-notebooks-tests
    tag: "latest"
    pullPolicy: IfNotPresent
