notebooks:
  image:
    repository: registry.dev.renku.ch/tasko.olevski/renku-images/renku-notebooks
    tag: "1.19.0"

  gitRpcServer:
    image:
      name: registry.dev.renku.ch/tasko.olevski/renku-images/git-rpc-server
      tag: "1.19.0"

  gitHttpsProxy:
    image:
      name: registry.dev.renku.ch/tasko.olevski/renku-images/git-https-proxy
      tag: "1.19.0"

  gitClone:
    image:
      name: registry.dev.renku.ch/tasko.olevski/renku-images/git-clone
      tag: "1.19.0"

  tests:
    image:
      repository: registry.dev.renku.ch/tasko.olevski/renku-images/renku-notebooks-tests
      tag: "1.19.0"

  k8sWatcher:
    image:
      repository: registry.dev.renku.ch/tasko.olevski/renku-images/k8s-watcher
      tag: 1.19.0

  ssh:
    image:
      repository: registry.dev.renku.ch/tasko.olevski/renku-images/ssh-jump-host
      tag: "1.19.0"
