serverOptions:
  cpu_request:
    displayName: CPU request
    type: enum
    default: 0.1
    options: [0.1, 0.5, 1.0, 2.0, 4.0]
  mem_request:
    displayName: Memory request
    type: enum
    default: 1G
    options: [1G, 2G, 4G]
  gpu_request:
    displayName: GPU request
    type: int
    default: 0
    range: [0, ]
  defaultUrl:
    displayName: default landing URL of the notebook server
    type: enum
    default: /lab
    options: [/lab]
  lfs_auto_fetch:
    displayName: Automatically fetch LFS data
    type: boolean
    default: false

gitlab:
  url: &gitlab_url https://gitlab.com
  registry:
    host: &gitlab_registry registry.gitlab.com

jupyterhub:
  rbac:
    enabled: true
  hub:
    cookieSecret: 7c232b97bda321be7e59b9834dfadbb89652da1e0150dff9b3dadb9aa8b4caab
    baseUrl: /
    services:
      notebooks:
        apiToken: notebookstoken
    extraEnv:
      IMAGE_REGISTRY: *gitlab_registry
      GITLAB_URL: *gitlab_url
  proxy:
    secretToken: f89ddee5ba10f2268fcefcd4e353235c255493095cd65addf29ebebf8df86255
    service:
      type: NodePort
      nodePorts:
        http: 31212
  auth:
    state:
      enabled: true
      cryptoKey: 86282f03d9886a64a46ee38f946e9ee27a600df4559584eeb90d0bfbd5a3dc0e
    gitlab:
      clientId: 75be9e2e28203c3c44272c72142a839956cfc07e1a0ab93a5d7c9ac6c7802b58
      clientSecret: 4bd8a67690d4a102436d15fa82b793d73046d350372ee6bd0302617298d08092

securityContext:
  enabled: false
