apiVersion: v1
kind: Pod
metadata:
  name: fuse-test
  annotations:
    container.apparmor.security.beta.kubernetes.io/myapp: unconfined
spec:
  tolerations:
    - effect: NoSchedule
      key: renku.io/dedicated
      operator: Equal
      value: user
  nodeName: worker-dev.renku-user-sessions-1
  containers:
    - name: myapp
      image: rclone/rclone:1.64
      securityContext:
        capabilities:
          add:
            - "SYS_ADMIN"
        privileged: false
        runAsUser: 1009
        runAsGroup: 1009
      command: ["sleep", "9999999"]
      resources:
        limits:
          smarter-devices/fuse: 1
        requests:
          smarter-devices/fuse: 1
