from .common import GenericError


class UserInputError(GenericError):
    """
    *Error codes: from 1000 to 1999*

    This category includes all the errors generated by user input. There is no unexpected
    error nor bugs here. The user should be able to address these issues.
    An example could be a wrong parameter (E.G. trying to access a non-existing repository,
    or a private repository without proper permissions).
    """

    default_message = "Invalid user input."
    default_status_code = 422
    default_code = 1000


class MissingResourceError(UserInputError):
    default_message = (
        "The resource you are requesting or "
        "is needed for your request does not exist."
    )
    default_status_code = 404
    default_code = 1404


class AuthenticationError(UserInputError):
    default_message = "Accessing the requested resource requires authentication."
    default_status_code = 401
    default_code = 1401


class DuplicateS3BucketNames(UserInputError):
    default_message = "The names of all mounted S3 buckets should be unique."
    default_status_code = 422
    default_code = 1402
