from dataclasses import dataclass

from .common import GenericError


@dataclass
class UserInputError(GenericError):
    """
    *Error codes: from 1000 to 1999*

    This category includes all the errors generated by user input. There is no unexpected
    error nor bugs here. The user should be able to address these issues.
    An example could be a wrong parameter (E.G. trying to access a non-existing repository,
    or a private repository without proper permissions).
    """

    message: str = "Invalid user input."
    code: int = 1000
    status_code: str = 422


@dataclass
class MissingResourceError(UserInputError):
    message: str = (
        "The resource you are requesting or is needed for your request does not exist."
    )
    code: int = 1404
    status_code: int = 404


@dataclass
class AuthenticationError(UserInputError):
    message: str = (
        "Accessing the requested resource requires authentication, please log in."
    )
    code: int = 1401
    status_code: int = 401


@dataclass
class DuplicateS3BucketNamesError(UserInputError):
    message: str = "The names of all mounted S3 buckets should be unique."
    code: int = 1402
    status_code: int = 422


@dataclass
class ImageParseError(UserInputError):
    message: str = "The provided image name cannot be parsed."
    code: int = 1403
    status_code: int = 422
