---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "notebooks.fullname" . }}-options
  labels:
    app: {{ template "notebooks.name" . }}
    chart: {{ template "notebooks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  server_options.json: |
    {{ toJson .Values.serverOptions }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hub-config-spawner
  labels:
    app: {{ template "notebooks.name" . }}
    chart: {{ template "notebooks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if .Values.jupyterhub.singleuser.sentryDsn }}
  SENTRY_DSN: {{ .Values.jupyterhub.singleuser.sentryDsn | quote }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notebook-helper-scripts
  labels:
    app: {{ template "notebooks.name" . }}
    chart: {{ template "notebooks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  pre-stop.sh: |
    #!/bin/bash
    UNCOMMITTED_CHANGES=`git status -s`
    UNPUSHED_COMMITS=`git log --branches --not --remotes`

    if [ -z "$UNCOMMITTED_CHANGES" ] && [ -z "$UNPUSHED_COMMITS" ]; then
      exit 0
    fi

    CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`
    LOCAL_SHA=`git rev-parse --short HEAD`
    REMOTE_SHA=`git rev-parse --short @{upstream}`

    if [ -z "$REMOTE_SHA" ]; then
      REMOTE_SHA="${LOCAL_SHA}"
    fi

    AUTOSAVE_BRANCH="renku/autosave/$JUPYTERHUB_USER/${CURRENT_BRANCH}/${REMOTE_SHA}/${LOCAL_SHA}"
    git checkout -b "$AUTOSAVE_BRANCH"
    git add .
    git commit -am "Auto-saving for $JUPYTERHUB_USER on branch $CURRENT_BRANCH and commit $LOCAL_SHA"
    git push origin "$AUTOSAVE_BRANCH"
    git checkout master
    git branch -D "$AUTOSAVE_BRANCH"
