apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "notebooks.fullname" . }}-remove-user-registry-secrets
  labels:
    app: {{ template "notebooks.name" . }}
    chart: {{ template "notebooks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: {{ if .Values.rbac.create }}"{{ template "notebooks.fullname" . }}"{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
          securityContext:
            runAsUser: 1000
          containers:
          - name: {{ .Chart.Name }}-remove-user-registry-secrets
            image: "{{ .Values.cull_secrets.image.repository }}:{{ .Values.cull_secrets.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["python", "/cull_secrets/clean_user_registry_secrets.py"]
            args: ["-n", "$(KUBERNETES_NAMESPACE)", "-a", "0.25"]
            env: 
              {{ if .Values.sentryDsn }}
              - name: SENTRY_DSN
                value: {{ .Values.sentryDsn | quote }}
              {{ end }}
              - name: KUBERNETES_NAMESPACE
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
