apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "notebooks.fullname" . }}
  labels:
    app: {{ template "notebooks.name" . }}
    chart: {{ template "notebooks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "notebooks.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "notebooks.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{ if eq .Values.securityContext.enabled true }}
      securityContext:
        runAsUser: 1000
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{ if eq .Values.debug true }}
            - name: FLASK_DEBUG
              value: "1"
            {{ end }}
            - name: JUPYTERHUB_API_TOKEN
              value: {{ .Values.jupyterhub_api_token }}
            - name: JUPYTERHUB_API_URL
            {{ if .Values.jupyterhub_api_url }}
              value: {{ .Values.jupyterhub_api_url }}
            {{ else }}
              value: {{ template "notebooks.http" . }}://{{ .Values.global.renku.domain }}{{ .Values.jupyterhub_base_url }}hub/api
            {{ end }}
            - name: JUPYTERHUB_SERVICE_PREFIX
              value: {{ .Values.jupyterhub_base_url }}services/notebooks/
            - name: JUPYTERHUB_BASE_URL
              value: {{ .Values.jupyterhub_base_url }}
            - name: JUPYTERHUB_CLIENT_ID
              value: {{ .Values.jupyterhub.hub.services.notebooks.oauth_client_id }}
            - name: GITLAB_REGISTRY_SECRET
              value: {{ template "renku.fullname" . }}-registry
            - name: GITLAB_URL
            {{ if .Values.gitlab_url }}
              value: {{ .Values.gitlab_url }}
            {{ else }}
              value: {{ template "notebooks.http" . }}://{{ .Values.global.renku.domain}}/gitlab
            {{ end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
              periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
              periodSeconds: 30
          resources:
{{ toYaml .Values.resources | indent 12 }}
      serviceAccountName: {{ if .Values.rbac.create }}"{{ template "notebooks.fullname" . }}"{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
