apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "notebooks.fullname" . }}
  labels:
    app: {{ template "notebooks.name" . }}
    chart: {{ template "notebooks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "notebooks.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "notebooks.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{ if .Values.userSessionPersistentVolumes.enabled }}
            - name: NOTEBOOKS_SESSION_PVS_ENABLED
              value: {{ .Values.userSessionPersistentVolumes.enabled | quote }}
            - name: NOTEBOOKS_SESSION_PVS_STORAGE_CLASS
              value: {{ .Values.userSessionPersistentVolumes.storageClass | quote}}
            {{ end }}
            - name: NOTEBOOKS_DEFAULT_IMAGE
              value: "{{ .Values.defaultSessionImage }}"
            - name: NOTEBOOKS_SERVER_OPTIONS_DEFAULTS_PATH
              value: /etc/renku-notebooks/server_options/server_defaults.json
            - name: NOTEBOOKS_SERVER_OPTIONS_UI_PATH
              value: /etc/renku-notebooks/server_options/server_options.json
            {{ if eq .Values.debug true }}
            - name: FLASK_DEBUG
              value: "1"
            {{ end }}
            - name: OIDC_CLIENT_ID
              value: {{ .Values.oidc.clientId }}
            - name: OIDC_CLIENT_SECRET
              value: {{ .Values.oidc.clientSecret }}
            - name: OIDC_AUTH_URL
              value: {{ .Values.oidc.auth_url }}
            - name: OIDC_TOKEN_URL
              value: {{ .Values.oidc.token_url }}
            - name: SESSION_HOST
              value: {{ .Values.session_ingress.host }}
            - name: SESSION_TLS_SECRET
              value: {{ .Values.session_ingress.tls_secret }}
            - name: SESSION_INGRESS_ANNOTATIONS
              value: {{ .Values.session_ingress.annotations | quote }}
            - name: GITLAB_URL
            {{ if .Values.gitlab.url }}
              value: {{ .Values.gitlab.url }}
            {{ else }}
              value: {{ template "notebooks.http" . }}://{{ .Values.global.renku.domain}}{{ .Values.global.gitlab.urlPrefix }}
            {{ end }}
            - name: IMAGE_REGISTRY
              value: {{ required "An image registry must be specified." .Values.gitlab.registry.host }}
            - name: GIT_SIDECAR_IMAGE
              value: "{{ .Values.git_sidecar.image.name }}:{{ .Values.git_sidecar.image.tag }}"
            - name: GIT_HTTPS_PROXY_IMAGE
              value: "{{ .Values.git_https_proxy.image.name }}:{{ .Values.git_https_proxy.image.tag }}"
            - name: ANONYMOUS_SESSIONS_ENABLED
              value: {{ .Values.global.anonymousSessions.enabled | quote }}
            - name: CRD_GROUP
              value: {{ .Values.amalthea.crdApiGroup }}
            - name: CRD_VERSION
              value: {{ .Values.amalthea.crdApiVersion }}
            - name: CRD_PLURAL
              value: {{ .Values.amalthea.crdNames.plural }}
            {{ if .Values.sentry.dsn }}
            - name: SENTRY_DSN
              value: {{ .Values.sentry.dsn | quote }}
            {{ end }}
            {{ if .Values.sentry.env }}
            - name: SENTRY_ENV
              value: {{ .Values.sentry.env | quote }}
            {{ end }}

            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: server-options
              mountPath: /etc/renku-notebooks/server_options
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 30
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: server-options
          configMap:
            name: {{ template "notebooks.fullname" . }}-options

      serviceAccountName: {{ if .Values.rbac.create }}"{{ template "notebooks.fullname" . }}"{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
