apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "notebooks.fullname" . }}-k8s-watcher
spec:
  podSelector:
    matchLabels:
      app: {{ template "notebooks.name" . }}-k8s-watcher
      release: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ template "notebooks.name" . }}
              release: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: http
