apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "notebooks.fullname" . }}
  labels:
    app: {{ template "notebooks.name" . }}
    chart: {{ template "notebooks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: uiserver
      ports:
        - port: 4000
          protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/component: jupyterserver
      app.kubernetes.io/name: amalthea
  policyTypes:
    - Ingress
