apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "notebooks.fullname" . }}
  labels:
    app: {{ template "notebooks.name" . }}
    chart: {{ template "notebooks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      component: "singleuser-server"
      app.kubernetes.io/component: {{ .Values.amalthea.crdNames.kind | lower  }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      # Allow ingress to a session pod's rpc server from anywhere
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 4000
