{{ if .Values.rbac.create }}
{{ range (append (list .Release.Namespace) .Values.sessionsNamespace | uniq) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "notebooks.fullname" $ }}
  namespace: {{ . }}
  labels:
    app: {{ template "notebooks.name" $ }}
    chart: {{ template "notebooks.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "notebooks.fullname" $ }}
subjects:
  - kind: ServiceAccount
    name: {{ template "notebooks.fullname" $ }}
    namespace: {{ $.Release.Namespace }}
{{ end }}
{{ end }}
