---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "notebooks.fullname" . }}
  labels:
    app: {{ template "notebooks.name" . }}
    chart: {{ template "notebooks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  jupyterhub-api-token: {{ required "Fill in .Values.jupyterhub.hub.services.notebooks.apiToken with `openssl rand -hex 32`" .Values.jupyterhub.hub.services.notebooks.apiToken | b64enc | quote }}
