---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "notebooks.fullname" . }}
  labels:
    app: {{ template "notebooks.name" . }}
    chart: {{ template "notebooks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.notebooksSessionSecret }}
  notebooks-session-secret: {{ .Values.notebooksSessionSecret | b64enc | quote }}
{{- else }}
  notebooks-session-secret: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
