apiVersion: v1
kind: Service
metadata:
  name: {{ template "notebooks.fullname" . }}
  labels:
    app: {{ template "notebooks.name" . }}
    chart: {{ template "notebooks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "notebooks.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "notebooks.fullname" . }}-k8s-watcher
  labels:
    app: {{ template "notebooks.name" . }}-k8s-watcher
    chart: {{ template "notebooks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "notebooks.name" . }}-k8s-watcher
    release: {{ .Release.Name }}
