apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "notebooks.fullname" . }}
  labels:
    app: {{ template "notebooks.name" . }}
    chart: {{ template "notebooks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  serviceName: {{ template "notebooks.fullname" . }}
  selector:
    matchLabels:
      app: {{ template "notebooks.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "notebooks.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            {{ if .Values.userSessionPersistentVolumes.enabled }}
            - name: NB_SESSIONS__STORAGE__PVS_ENABLED
              value: {{ .Values.userSessionPersistentVolumes.enabled | quote }}
            - name: NB_SESSIONS__STORAGE__PVS_STORAGE_CLASS
              value: {{ .Values.userSessionPersistentVolumes.storageClass | quote}}
            {{ end }}
            - name: NB_SESSIONS__STORAGE__USE_EMPTY_DIR_SIZE_LIMIT
              value: {{ .Values.userSessionPersistentVolumes.useEmptyDirSizeLimit | quote }}
            - name: NB_SESSIONS__DEFAULT_IMAGE
              value: "{{ .Values.defaultSessionImage }}"
            - name: NB_SERVER_OPTIONS__DEFAULTS_PATH
              value: /etc/renku-notebooks/server_options/server_defaults.json
            - name: NB_SERVER_OPTIONS__UI_CHOICES_PATH
              value: /etc/renku-notebooks/server_options/server_options.json
            {{ if eq .Values.debug true }}
            - name: FLASK_DEBUG
              value: "1"
            {{ end }}
            - name: NB_SESSIONS__OIDC__CLIENT_ID
              value: {{ .Values.oidc.clientId }}
            - name: NB_SESSIONS__OIDC__CLIENT_SECRET
              value: {{ .Values.oidc.clientSecret }}
            - name: NB_SESSIONS__OIDC__AUTH_URL
              value: {{ .Values.oidc.authUrl }}
            - name: NB_SESSIONS__OIDC__TOKEN_URL
              value: {{ .Values.oidc.tokenUrl }}
            - name: NB_SESSIONS__OIDC__ALLOW_UNVERIFIED_EMAIL
              value: {{ .Values.oidc.allowUnverifiedEmail | quote }}
            - name: NB_SESSIONS__INGRESS__HOST
              value: {{ .Values.sessionIngress.host }}
            - name: NB_SESSIONS__INGRESS__TLS_SECRET
              value: {{ .Values.sessionIngress.tlsSecret }}
            - name: NB_SESSIONS__INGRESS__ANNOTATIONS
              value: |
                {{- .Values.sessionIngress.annotations | toYaml | nindent 16 }}
            - name: NB_GIT__URL
            {{ if .Values.gitlab.url }}
              value: {{ .Values.gitlab.url }}
            {{ else }}
              value: {{ template "notebooks.http" . }}://{{ .Values.global.renku.domain}}{{ .Values.global.gitlab.urlPrefix }}
            {{ end }}
            - name: NB_GIT__REGISTRY
              value: {{ required "An image registry must be specified." .Values.gitlab.registry.host }}
            - name: NB_SESSIONS__GIT_RPC_SERVER__IMAGE
              value: "{{ .Values.gitRpcServer.image.name }}:{{ .Values.gitRpcServer.image.tag }}"
            - name: NB_SESSIONS__GIT_PROXY__IMAGE
              value: "{{ .Values.gitHttpsProxy.image.name }}:{{ .Values.gitHttpsProxy.image.tag }}"
            - name: NB_SESSIONS__GIT_CLONE__IMAGE
              value: "{{ .Values.gitClone.image.name }}:{{ .Values.gitClone.image.tag }}"
            - name: NB_ANONYMOUS_SESSIONS_ENABLED
              value: {{ .Values.global.anonymousSessions.enabled | quote }}
            - name: NB_SESSIONS__CULLING__REGISTERED__IDLE_SECONDS
              value: {{ .Values.culling.idleThresholdSeconds.registered | quote }}
            - name: NB_SESSIONS__CULLING__ANONYMOUS__IDLE_SECONDS
              value: {{ .Values.culling.idleThresholdSeconds.anonymous | quote }}
            - name: NB_SESSIONS__CULLING__REGISTERED__MAX_AGE_SECONDS
              value: {{ .Values.culling.maxAgeSecondsThreshold.registered | quote }}
            - name: NB_SESSIONS__CULLING__ANONYMOUS__MAX_AGE_SECONDS
              value: {{ .Values.culling.maxAgeSecondsThreshold.anonymous | quote }}
            - name: NB_AMALTHEA__GROUP
              value: {{ .Values.amalthea.crdApiGroup }}
            - name: NB_AMALTHEA__VERSION
              value: {{ .Values.amalthea.crdApiVersion }}
            - name: NB_AMALTHEA__PLURAL
              value: {{ .Values.amalthea.crdNames.plural }}
            - name: NB_SENTRY__ENABLED
              value: {{ .Values.sentry.enabled | quote }}
            - name: NB_SENTRY__DSN
              value: {{ .Values.sentry.dsn | quote }}
            - name: NB_SENTRY__ENV
              value: {{ .Values.sentry.environment | quote }}
            - name: NB_SENTRY__SAMPLE_RATE
              value: {{ .Values.sentry.sampleRate | quote }}
            - name: SENTRY_RELEASE
              value: {{ .Chart.Version | quote }}
            - name: NB_SESSIONS__GIT_CLONE__SENTRY__ENABLED
              value: {{ .Values.sessionSentry.gitClone.enabled | quote }}
            - name: NB_SESSIONS__GIT_CLONE__SENTRY__DSN
              value: {{ .Values.sessionSentry.gitClone.dsn | quote }}
            - name: NB_SESSIONS__GIT_CLONE__SENTRY__ENV
              value: {{ .Values.sessionSentry.gitClone.environment | quote }}
            - name: NB_SESSIONS__GIT_CLONE__SENTRY__SAMPLE_RATE
              value: {{ .Values.sessionSentry.gitClone.sampleRate | quote }}
            - name: NB_SESSIONS__GIT_RPC_SERVER__SENTRY__ENABLED
              value: {{ .Values.sessionSentry.sidecar.enabled | quote }}
            - name: NB_SESSIONS__GIT_RPC_SERVER__SENTRY__DSN
              value: {{ .Values.sessionSentry.sidecar.dsn | quote }}
            - name: NB_SESSIONS__GIT_RPC_SERVER__SENTRY__ENV
              value: {{ .Values.sessionSentry.sidecar.environment | quote }}
            - name: NB_SESSIONS__GIT_RPC_SERVER__SENTRY__SAMPLE_RATE
              value: {{ .Values.sessionSentry.sidecar.sampleRate | quote }}
            - name: NB_SESSIONS__CA_CERTS__IMAGE
              value: "{{ .Values.global.certificates.image.repository }}:{{ .Values.global.certificates.image.tag }}"
            - name: NB_SESSIONS__CA_CERTS__SECRETS
              value: |
                {{- .Values.global.certificates.customCAs | toYaml | nindent 16 }}
            {{- with .Values.sessionNodeSelector }}
            - name: NB_SESSIONS__NODE_SELECTOR
              value: |
                {{- toYaml . | nindent 16 }}
            {{- end }}
            {{- with .Values.sessionAffinity }}
            - name: NB_SESSIONS__AFFINITY
              value: |
                {{- toYaml . | nindent 16 }}
            {{- end }}
            {{- with .Values.sessionTolerations }}
            - name: NB_SESSIONS__TOLERATIONS
              value: |
                {{- toYaml . | nindent 16 }}
            {{- end }}
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            {{- include "certificates.env.python" . | nindent 12 }}
            - name: NB_SESSIONS__ENFORCE_CPU_LIMITS
              value: {{ .Values.enforceCPULimits | quote }}
            - name: NB_S3_MOUNTS_ENABLED
              value: {{ .Values.cloudstorage.s3.enabled | quote }}
            - name: NB_SESSIONS__TERMINATION_GRACE_PERIOD_SECONDS
              value: {{ .Values.sessionAutosave.terminationGracePeriodSeconds | quote }}
            - name: NB_SESSIONS__AUTOSAVE_MINIMUM_LFS_FILE_SIZE_BYTES
              value: {{ .Values.sessionAutosave.minimumLFSFileSizeBytes | quote }}
            - name: NB_VERSION
              value: {{ .Values.image.tag | quote }}
            - name: NB_K8S__NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: server-options
              mountPath: /etc/renku-notebooks/server_options
            {{- include "certificates.volumeMounts.system" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
        {{- include "certificates.initContainer" . | nindent 8 }}
        - name: k8s-resource-schema-migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CRD_GROUP
              value: {{ .Values.amalthea.crdApiGroup }}
            - name: CRD_VERSION
              value: {{ .Values.amalthea.crdApiVersion }}
            - name: CRD_PLURAL
              value: {{ .Values.amalthea.crdNames.plural }}
            - name: K8S_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          command:
            - poetry
            - run
          args:
            - python
            - resource_schema_migrations/run_all.py
      volumes:
        - name: server-options
          configMap:
            name: {{ template "notebooks.fullname" . }}-options
        {{- include "certificates.volumes" . | nindent 8 }}

      serviceAccountName: {{ if .Values.rbac.create }}"{{ template "notebooks.fullname" . }}"{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | indent 8 }}
    {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ template "notebooks.name" . }}
                topologyKey: "kubernetes.io/hostname"
        {{- with .Values.affinity }}
        {{ toYaml . | indent 8 }}
        {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
