apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "notebooks.fullname" . }}
  labels:
    app: {{ template "notebooks.name" . }}
    chart: {{ template "notebooks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  serviceName: {{ template "notebooks.fullname" . }}
  selector:
    matchLabels:
      app: {{ template "notebooks.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "notebooks.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{ if .Values.userSessionPersistentVolumes.enabled }}
            - name: NOTEBOOKS_SESSION_PVS_ENABLED
              value: {{ .Values.userSessionPersistentVolumes.enabled | quote }}
            - name: NOTEBOOKS_SESSION_PVS_STORAGE_CLASS
              value: {{ .Values.userSessionPersistentVolumes.storageClass | quote}}
            {{ end }}
            - name: USE_EMPTY_DIR_SIZE_LIMIT
              value: {{ .Values.userSessionPersistentVolumes.useEmptyDirSizeLimit | quote }}
            - name: NOTEBOOKS_DEFAULT_IMAGE
              value: "{{ .Values.defaultSessionImage }}"
            - name: NOTEBOOKS_SERVER_OPTIONS_DEFAULTS_PATH
              value: /etc/renku-notebooks/server_options/server_defaults.json
            - name: NOTEBOOKS_SERVER_OPTIONS_UI_PATH
              value: /etc/renku-notebooks/server_options/server_options.json
            {{ if eq .Values.debug true }}
            - name: FLASK_DEBUG
              value: "1"
            {{ end }}
            - name: OIDC_CLIENT_ID
              value: {{ .Values.oidc.clientId }}
            - name: OIDC_CLIENT_SECRET
              value: {{ .Values.oidc.clientSecret }}
            - name: OIDC_AUTH_URL
              value: {{ .Values.oidc.authUrl }}
            - name: OIDC_TOKEN_URL
              value: {{ .Values.oidc.tokenUrl }}
            - name: OIDC_ALLOW_UNVERIFIED_EMAIL
              value: {{ .Values.oidc.allowUnverifiedEmail | quote }}
            - name: SESSION_HOST
              value: {{ .Values.sessionIngress.host }}
            - name: SESSION_TLS_SECRET
              value: {{ .Values.sessionIngress.tlsSecret }}
            - name: SESSION_INGRESS_ANNOTATIONS
              value: |
                {{- .Values.sessionIngress.annotations | toYaml | nindent 16 }}
            - name: GITLAB_URL
            {{ if .Values.gitlab.url }}
              value: {{ .Values.gitlab.url }}
            {{ else }}
              value: {{ template "notebooks.http" . }}://{{ .Values.global.renku.domain}}{{ .Values.global.gitlab.urlPrefix }}
            {{ end }}
            - name: IMAGE_REGISTRY
              value: {{ required "An image registry must be specified." .Values.gitlab.registry.host }}
            - name: GIT_RPC_SERVER_IMAGE
              value: "{{ .Values.gitRpcServer.image.name }}:{{ .Values.gitRpcServer.image.tag }}"
            - name: GIT_HTTPS_PROXY_IMAGE
              value: "{{ .Values.gitHttpsProxy.image.name }}:{{ .Values.gitHttpsProxy.image.tag }}"
            - name: GIT_CLONE_IMAGE
              value: "{{ .Values.gitClone.image.name }}:{{ .Values.gitClone.image.tag }}"
            - name: ANONYMOUS_SESSIONS_ENABLED
              value: {{ .Values.global.anonymousSessions.enabled | quote }}
            - name: CULLING_REGISTERED_IDLE_SESSIONS_THRESHOLD_SECONDS
              value: {{ .Values.culling.idleThresholdSeconds.registered | quote }}
            - name: CULLING_ANONYMOUS_IDLE_SESSIONS_THRESHOLD_SECONDS
              value: {{ .Values.culling.idleThresholdSeconds.anonymous | quote }}
            - name: CULLING_REGISTERED_MAX_AGE_THRESHOLD_SECONDS
              value: {{ .Values.culling.maxAgeSecondsThreshold.registered | quote }}
            - name: CULLING_ANONYMOUS_MAX_AGE_THRESHOLD_SECONDS
              value: {{ .Values.culling.maxAgeSecondsThreshold.anonymous | quote }}
            - name: CRD_GROUP
              value: {{ .Values.amalthea.crdApiGroup }}
            - name: CRD_VERSION
              value: {{ .Values.amalthea.crdApiVersion }}
            - name: CRD_PLURAL
              value: {{ .Values.amalthea.crdNames.plural }}
            {{ if .Values.sentry.dsn }}
            - name: SENTRY_DSN
              value: {{ .Values.sentry.dsn | quote }}
            {{ end }}
            {{ if .Values.sentry.env }}
            - name: SENTRY_ENV
              value: {{ .Values.sentry.env | quote }}
            {{ end }}
            - name: CERTIFICATES_IMAGE
              value: "{{ .Values.global.certificates.image.repository }}:{{ .Values.global.certificates.image.tag }}"
            - name: CUSTOM_CA_CERTS_SECRETS
              value: |
                {{- .Values.global.certificates.customCAs | toYaml | nindent 16 }}
            {{- include "certificates.env.python" . | nindent 12 }}
            {{- with .Values.sessionNodeSelector }}
            - name: SESSION_NODE_SELECTOR
              value: |
                {{- toYaml . | nindent 16 }}
            {{- end }}
            {{- with .Values.sessionAffinity }}
            - name: SESSION_AFFINITY
              value: |
                {{- toYaml . | nindent 16 }}
            {{- end }}
            {{- with .Values.sessionTolerations }}
            - name: SESSION_TOLERATIONS
              value: |
                {{- toYaml . | nindent 16 }}
            {{- end }}
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: ENFORCE_CPU_LIMITS
              value: {{ .Values.enforceCPULimits | quote }}
            - name: S3_MOUNTS_ENABLED
              value: {{ .Values.s3mounts.enabled | quote }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: server-options
              mountPath: /etc/renku-notebooks/server_options
            {{- include "certificates.volumeMounts.system" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 30
          resources:
{{ toYaml .Values.resources | indent 12 }}
      initContainers:
        - name: k8s-resource-schema-migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CRD_GROUP
              value: {{ .Values.amalthea.crdApiGroup }}
            - name: CRD_VERSION
              value: {{ .Values.amalthea.crdApiVersion }}
            - name: CRD_PLURAL
              value: {{ .Values.amalthea.crdNames.plural }}
            - name: K8S_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          command:
            - python
          args:
            - /resource_schema_migrations/run_all.py
        {{- include "certificates.initContainer" . | nindent 8 }}
      volumes:
        - name: server-options
          configMap:
            name: {{ template "notebooks.fullname" . }}-options
        {{- include "certificates.volumes" . | nindent 8 }}

      serviceAccountName: {{ if .Values.rbac.create }}"{{ template "notebooks.fullname" . }}"{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
