apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "notebooks.fullname" . }}
  labels:
    app: {{ template "notebooks.name" . }}
    chart: {{ template "notebooks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  serviceName: {{ template "notebooks.fullname" . }}
  selector:
    matchLabels:
      app: {{ template "notebooks.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "notebooks.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            {{ if eq .Values.debug true }}
            - name: FLASK_DEBUG
              value: "1"
            {{ end }}
            - name: SENTRY_RELEASE
              value: {{ .Chart.Version | quote }}
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: CONFIG_FILE
              value: /etc/renku-notebooks/config/config.hocon
            {{- include "certificates.env.python" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: server-options
              mountPath: /etc/renku-notebooks/server_options
            - name: notebooks-config
              mountPath: /etc/renku-notebooks/config
            {{- include "certificates.volumeMounts.system" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
        {{- include "certificates.initContainer" . | nindent 8 }}
        - name: k8s-resource-schema-migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CRD_GROUP
              value: {{ .Values.amalthea.crdApiGroup }}
            - name: CRD_VERSION
              value: {{ .Values.amalthea.crdApiVersion }}
            - name: CRD_PLURAL
              value: {{ .Values.amalthea.crdNames.plural }}
            - name: K8S_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          command:
            - poetry
            - run
          args:
            - python
            - resource_schema_migrations/run_all.py
      volumes:
        - name: server-options
          configMap:
            name: {{ template "notebooks.fullname" . }}-options
        - name: notebooks-config
          configMap:
            name: {{ template "notebooks.fullname" . }}-config
        {{- include "certificates.volumes" . | nindent 8 }}

      serviceAccountName: {{ if .Values.rbac.create }}"{{ template "notebooks.fullname" . }}"{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | indent 8 }}
    {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ template "notebooks.name" . }}
                topologyKey: "kubernetes.io/hostname"
        {{- with .Values.affinity }}
        {{ toYaml . | indent 8 }}
        {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
