{{- if .Values.tests.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: "{{ template "notebooks.fullname" . }}-integration-test"
  annotations:
    "helm.sh/hook": test
spec:
  serviceAccountName: {{ if $.Values.rbac.create }}"{{ template "notebooks.fullname" . }}"{{ else }}"{{ $.Values.rbac.serviceAccountName }}"{{ end }}
  containers:
{{- range .Values.tests.sessionTypes }}
    - name: {{ printf "%s-integration-test-%s" (include "notebooks.fullname" $) . }}
      image: "{{ $.Values.tests.image.repository }}:{{ $.Values.tests.image.tag }}"
      imagePullPolicy: {{ $.Values.tests.image.pullPolicy }}
      env:
        - name: SESSION_HOST
          value: {{ $.Values.sessionIngress.host | quote }}
        - name: OIDC_CLIENT_ID
          value: {{ $.Values.oidc.clientId | quote }}
        - name: OIDC_CLIENT_SECRET
          value: {{ $.Values.oidc.clientSecret | quote }}
        - name: OIDC_TOKEN_URL
          value: {{ $.Values.oidc.tokenUrl | quote }}
        - name: OIDC_AUTH_URL
          value: {{ $.Values.oidc.authUrl | quote }}
        - name: OIDC_ISSUER
          value: {{ $.Values.tests.oidc_issuer | quote }}
        - name: OIDC_ALLOW_UNVERIFIED_EMAIL
          value: {{ $.Values.oidc.allowUnverifiedEmail | quote }}
        - name: GITLAB_URL
          value: {{ $.Values.gitlab.url | quote }}
        - name: GITLAB_REGISTRY
          value: {{ $.Values.gitlab.registry.host | quote }}
        - name: GITLAB_TOKEN
          value: {{ $.Values.tests.gitlab_token | quote }}
        - name: NOTEBOOKS_BASE_URL
          value: {{ printf "http://%s" (include "notebooks.fullname" $) }}
        - name: NOTEBOOKS_DEFAULT_IMAGE
          value: "{{ $.Values.defaultSessionImage }}"
        - name: NOTEBOOKS_SERVER_OPTIONS_DEFAULTS_PATH
          value: /etc/renku-notebooks/server_options/server_defaults.json
        - name: NOTEBOOKS_SERVER_OPTIONS_UI_PATH
          value: /etc/renku-notebooks/server_options/server_options.json
        - name: SESSION_TYPE
          value: {{ . | quote }}
        - name: CULLING_REGISTERED_IDLE_SESSIONS_THRESHOLD_SECONDS
          value: {{ $.Values.culling.idleThresholdSeconds.registered | quote }}
        - name: CULLING_ANONYMOUS_IDLE_SESSIONS_THRESHOLD_SECONDS
          value: {{ $.Values.culling.idleThresholdSeconds.anonymous | quote }}
        - name: CULLING_REGISTERED_MAX_AGE_THRESHOLD_SECONDS
          value: {{ $.Values.culling.maxAgeSecondsThreshold.registered | quote }}
        - name: CULLING_ANONYMOUS_MAX_AGE_THRESHOLD_SECONDS
          value: {{ $.Values.culling.maxAgeSecondsThreshold.anonymous | quote }}
        - name: CRD_GROUP
          value: {{ $.Values.amalthea.crdApiGroup }}
        - name: CRD_VERSION
          value: {{ $.Values.amalthea.crdApiVersion }}
        - name: CRD_PLURAL
          value: {{ $.Values.amalthea.crdNames.plural }}
        - name: SESSION_INGRESS_ANNOTATIONS
          value: |
            {{- $.Values.sessionIngress.annotations | toYaml | nindent 12 }}
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        {{- with $.Values.sessionNodeSelector }}
        - name: SESSION_NODE_SELECTOR
          value: |
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with $.Values.sessionAffinity }}
        - name: SESSION_AFFINITY
          value: |
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with $.Values.sessionTolerations }}
        - name: SESSION_TOLERATIONS
          value: |
            {{- toYaml . | nindent 12 }}
        {{- end }}
        - name: ENFORCE_CPU_LIMITS
          value: {{ $.Values.enforceCPULimits | quote }}
        - name: S3_MOUNTS_ENABLED
          value: {{ $.Values.cloudstorage.s3.enabled | quote }}
        - name: SESSION_TERMINATION_GRACE_PERIOD_SECONDS
          value: {{ .Values.sessionAutosave.terminationGracePeriodSeconds | quote }}
      command:
        - pipenv
        - run
        - pytest
        - -v
        - tests/integration
      volumeMounts:
        - name: server-options
          mountPath: /etc/renku-notebooks/server_options
{{- end }}
  restartPolicy: Never
  volumes:
    - name: server-options
      configMap:
        name: {{ template "notebooks.fullname" . }}-options
{{- end }}