{{- if .Values.tests.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: "{{ template "notebooks.fullname" . }}-integration-test"
  annotations:
    "helm.sh/hook": test
spec:
  serviceAccountName: {{ template "notebooks.fullname" . }}-test
  containers:
{{- range .Values.tests.sessionTypes }}
    - name: {{ printf "%s-integration-test-%s" (include "notebooks.fullname" $) . }}
      image: "{{ $.Values.tests.image.repository }}:{{ $.Values.tests.image.tag }}"
      imagePullPolicy: {{ $.Values.tests.image.pullPolicy }}
      env:
        - name: SESSION_TYPE
          value: {{ . | quote }}
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CONFIG_FILE
          value: /etc/renku-notebooks/config/config.hocon
      command:
        - poetry
        - run
        - pytest
        - -v
        - tests/integration
      volumeMounts:
        - name: server-options
          mountPath: /etc/renku-notebooks/server_options
        - name: notebooks-config
          mountPath: /etc/renku-notebooks/config
{{- end }}
  restartPolicy: Never
  volumes:
    - name: server-options
      configMap:
        name: {{ template "notebooks.fullname" . }}-options
    - name: notebooks-config
      configMap:
        name: {{ template "notebooks.fullname" . }}-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "notebooks.fullname" . }}-test
  labels:
    app: {{ template "notebooks.name" . }}
    chart: {{ template "notebooks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - secrets
    verbs:
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - {{ .Values.amalthea.crdApiGroup }}
    resources:
      - {{ .Values.amalthea.crdNames.plural }}
    verbs:
      - create
      - update
      - delete
      - patch
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "notebooks.fullname" . }}-test
  labels:
    app: {{ template "notebooks.name" . }}
    chart: {{ template "notebooks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "notebooks.fullname" . }}-test
subjects:
  - kind: ServiceAccount
    name: {{ template "notebooks.fullname" . }}-test
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "notebooks.fullname" . }}-test
  labels:
    app: {{ template "notebooks.name" . }}
    chart: {{ template "notebooks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
