name: CI

on: [push]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --deploy --system --dev
    - name: Test with pytest
      run: |
        pytest tests/unit renku_notebooks

  test-git-proxy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'
    - name: Test git proxy
      run: |
        cd git-https-proxy
        go test -v
  
  test-git-services:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        cd git_services
        poetry install
    - name: Test git services
      run: |
        cd git-https-proxy
        pytest -v tests 

  test-chart:
    needs: test
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'"
    steps:
      - uses: actions/checkout
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install helm
        uses: azure/setup-helm@v1
      - name: Test chart
        run: |
          PATH=${{ runner.temp }}/linux-amd64/:$PATH
          helm lint helm-chart/renku-notebooks
      - name: Build chart and images
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --deploy --system --dev
          chartpress

  publish-chart-tagged:
    runs-on: ubuntu-latest
    needs: 
    - test-chart
    - test
    - test-git-proxy
    - test-git-services
    if: "startsWith(github.ref, 'refs/tags/')"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: set up environment variables
      run: |
        echo "GIT_USER=Renku Bot" >> $GITHUB_ENV
        echo "GIT_EMAIL=renku@datascience.ch" >> $GITHUB_ENV
    - name: Push tagged chart and images
      uses: SwissDataScienceCenter/renku-actions/publish-chart@v0.5.1
      env:
        CHART_NAME: renku-notebooks
        GITHUB_TOKEN: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.RENKU_DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.RENKU_DOCKER_PASSWORD }}
    - name: Wait for chart to get published
      run: sleep 120
    - name: Update component version
      uses: SwissDataScienceCenter/renku-actions/update-component-version@v0.5.1
      env:
        CHART_NAME: renku-notebooks
        GITHUB_TOKEN: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}

  push-latest-image:
    runs-on: ubuntu-latest
    needs: publish-chart-tagged
    if: "startsWith(github.ref, 'refs/tags/')"
    steps:
    - uses: actions/checkout@v2
    - uses: azure/setup-helm@v1
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Push latest image
      env:
        DOCKER_USERNAME: ${{ secrets.RENKU_DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.RENKU_DOCKER_PASSWORD }}
      run: |
        pip install --user pipx
        pipx ensurepath
        pipx install pipenv
        pipenv install --dev
        echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
        helm dep update helm-chart/renku-notebooks
        pipenv run chartpress --push --tag latest
