name: Integration tests

on: [push]
  # push: {}
  # pull_request:
  #   types:
  #   - opened
  #   - edited
  #   - synchronize
  #   - reopened
  #   - closed

jobs:
  deploy-pr:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.1.0
      with:
        cluster_name: kind
    - name: Create values file
      env:
        OIDC_GITLAB_CLIENT_ID: ${{ secrets.OIDC_GITLAB_CLIENT_ID }}
        OIDC_GITLAB_CLIENT_SECRET: ${{ secrets.OIDC_GITLAB_CLIENT_SECRET }}
        TEST_DEV_GITLAB_TOKEN: ${{ secrets.TEST_DEV_GITLAB_TOKEN }}
      run: |
        cat <<EOF > test-values.yaml
        amalthea:
          scope:
            namespaces: [default]
          deployCrd: true
          networkPolicies:
            enabled: true
            ingressSelectorLabels: "{}"
            ingressNamespaceSelectorLabels: "{}"
        global:
          anonymousSessions:
            enabled: true
        userSessionPersistentVolumes:
          enabled: true
          storageClass: standard
        gitlab:
          registry:
            host: registry.dev.renku.ch
          url: https://dev.renku.ch/gitlab
        oidc:
          client_id: $OIDC_GITLAB_CLIENT_ID
          client_secret: $OIDC_GITLAB_CLIENT_SECRET
          token_url: https://dev.renku.ch/gitlab/oauth/token
          auth_url: https://dev.renku.ch/gitlab/oauth/authorize
        session_ingress:
          host: test.host.com
          tls_secret: dummy-tls-secret
        tests:
          enabled: true
          oidc_issuer: https://dev.renku.ch/gitlab
          gitlab_token: $TEST_DEV_GITLAB_TOKEN
        debug: false
        EOF
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Setup chartpress
      run: |
        pip install --user pipx
        pipx ensurepath
        pipx install pipenv
        pipenv install --dev
        pipenv run chartpress
    - name: Install Helm Chart
      run: |
        helm dep update helm-chart/renku-notebooks
        helm install renku-notebooks helm-chart/renku-notebooks -f test-values.yaml
    - name: Helm Test
      run: |
        helm test renku-notebooks --timeout 10m0s
        kubectl logs renku-notebooks-integration-test -c renku-notebooks-integration-test-registered
    - name: Extract logs
      if: always()
      run: |
        mkdir kind-logs
        kind export logs ./kind-logs
        ls -la kind-logs/kind-control-plane/pods/
        ls -la kind-logs/kind-control-plane/pods/default_renku-notebooks-integration-test_*/*
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-logs
        path: |
          kind-logs/kind-control-plane/pods/**/renku-notebooks-integration-test-anonymous/
          kind-logs/kind-control-plane/pods/**/renku-notebooks-integration-test-registered/
  