name: Integration tests

on:
  pull_request:
    types:
    - synchronize

jobs:
  integration-test:
    strategy:
      matrix:
        session-type: ["registered", "anonymous"]
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.1.0
      with:
        cluster_name: kind
        wait: 10m0s
        version: v0.11.1
    - name: Create values file
      env:
        OIDC_GITLAB_CLIENT_ID: ${{ secrets.OIDC_GITLAB_CLIENT_ID }}
        OIDC_GITLAB_CLIENT_SECRET: ${{ secrets.OIDC_GITLAB_CLIENT_SECRET }}
        TEST_DEV_GITLAB_TOKEN: ${{ secrets.TEST_DEV_GITLAB_TOKEN }}
      run: |
        cat <<EOF > test-values.yaml
        amalthea:
          scope:
            namespaces: [default]
          deployCrd: true
        global:
          anonymousSessions:
            enabled: true
        userSessionPersistentVolumes:
          enabled: true
          storageClass: standard
        gitlab:
          registry:
            host: registry.dev.renku.ch
          url: https://dev.renku.ch/gitlab
        oidc:
          clientId: $OIDC_GITLAB_CLIENT_ID
          clientSecret: $OIDC_GITLAB_CLIENT_SECRET
          token_url: https://dev.renku.ch/gitlab/oauth/token
          auth_url: https://dev.renku.ch/gitlab/oauth/authorize
        session_ingress:
          host: test.host.com
          tls_secret: dummy-tls-secret
        tests:
          sessionTypes:
            - ${{ matrix.session-type }}
          enabled: true
          oidc_issuer: https://dev.renku.ch/gitlab
          gitlab_token: $TEST_DEV_GITLAB_TOKEN
        debug: false
        EOF
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Setup chartpress
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        pip install --user pipx
        pipx ensurepath
        pipx install pipenv
        pipenv install --dev
        echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
        pipenv run chartpress --push
    - name: Install Helm Chart
      run: |
        helm dep update helm-chart/renku-notebooks
        helm install renku-notebooks helm-chart/renku-notebooks -f test-values.yaml --wait --timeout 5m0s
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   with:
    #     limit-access-to-actor: true
    - name: Helm Test
      run: |
        helm test renku-notebooks --timeout 60m0s --logs
  