name: Cleanup old CI deployments

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '40 23 * * *'
  push:
    
  
jobs:
  cleanup-old-cis:
    runs-on: ubuntu-20.04
    steps:
    - name: Cleanup
      uses: SwissDataScienceCenter/renku-actions/cleanup-renku-ci-deployments@test-and-cleanup-action
      env:
        RENKUBOT_KUBECONFIG: ${{ secrets.RENKUBOT_DEV_KUBECONFIG }}
        HELM_RELEASE_REGEX: "renku-ci-nb-[0-9]+"
        GITLAB_TOKEN: ${{ secrets.DEV_GITLAB_TOKEN }}
        MAX_AGE_SECONDS: 999999999999999999999999999